### ISSUE TITLE
Rotation of Cables

### ISSUE THREAD

**Issue by LezChap** [Lothrazar/Storage-Network#148]
Minecraft version & Mod Version:
SimpleStorageNetwork-1.12.2-1.7.2  (in Sky Factory 4.0.1)

Single player or Server:
SSP

Describe problem (what you were doing / what happened):
Rotation of Storage Link Cables, and other inventory-connecting cables are counter-intuitive and broken.  They always connect to the same inventory regardless of which inventory they're placed "on" (when multiple inventories are adjacent to each other).  I can rotate them visually with a crescent hammer from TE, but functionally they do not change the inventory they are "looking" at.

Cables should connect to the inventory they are placed on (if I'm looking at an inventory when I place the cable, that's the one it should connect to).  Rotating with a wrench should change the inventory it's looking in/at, not just the direction it's rendered to point.

**Comment by Lothrazar** [comment]
Yep that makes sense and is a quick fix

**Comment by Lothrazar** [comment]
Fixed it latest release

**Comment by PortalHubYT** [comment]
![image](https://user-images.githubusercontent.com/81389009/229516695-edcfc3e0-c3fe-4ac1-959e-605fcb9239ac.png)
shift clicking on this oak drawers result in this, 1.19.2-1.6.4:
![image](https://user-images.githubusercontent.com/81389009/229516743-2afbf8e6-4a4c-4acb-8468-9d5a9fbc0f91.png)

which leads me to think this was broken again or not properly fixed?
using a wrench does the same thing as OP mentionned, turns the cable visually but not functionally.

This issue seems to relate to orientation because I can't reproduce it facing another axis, it feels like it default to a certain orientation, creating this unintended behavior

for anyone facing the same problem, if you have Mekanism in your modpack, I'd recommend packing the adjacent inventories with a cardboard box, connecting the link cable, then you can unpack the problematic inventories
