### ISSUE TITLE
Storage Request Table messes up inventory order

### ISSUE THREAD

**Issue by RainerZufahl** [Lothrazar/Storage-Network#179]
Minecraft version & Mod Version: 1.12.2 / 1.7.4

Single player or Server: Server

Describe problem (what you were doing / what happened): When opening the Storage Request Table, it will reorder all the items in my inventory by pushing them one slot to the right. This is purely visual, clicking on any item will reset the display.

Here is a gif of the issue: https://imgur.com/OSomjLC

Crash log (if any): no crashing

**Comment by GentlemanGnu** [comment]
we've had a similar issue on our server (noted by duely below) did you happen to upgrade your version on the same world?  the issue sounds exactly the same.  generating a new world, and we couldn't replicate the issue.  Wonder if this has anything to do with it??

Really looking forward to this mod being updated.  Please Lothrazaar?

**Comment by RainerZufahl** [comment]
Yes, we upgraded the mod on an existing map (upgrading from 1.5.7). I haven't tried creating a new map on the new version.

**Comment by Darkmega18** [comment]
I'm having this same issue also on a recently made server. We previously had 1.7.4 but hadn't had a storage system yet made anywhere at all. But I had recently gotten us to update to 1.7.5 this morning as twitch launcher was showing me mod updates and I like to keep things up to date. I had just made a storage system, happy that I shouldn't have anymore hoarding and sorting issues anymore and then I notice this bug happening.

it's just as the picture from rainer shows, when I open the requester my inventory is shifted one square sideways for all slots. it seems to react fine when putting stuff in and work such as how I've been emptying all our chests into it by carrying them to the system, breaking them then mass importing stuff through the screen. 
but the issue comes when taking stuff out and placing them into the inventory manually as when I leave the screen I must click something in my inventory to make it all snap back to it's original spot, which if that happens it can cause some phantom item visuals etc or some heart attacks with items being yeeted into bugland. :V

**Comment by Darkmega18** [comment]
I can further confirm that this doesn't happen in a new world. I didn't have a new world with a previous version to test singleplayer having the mod updated half way through so thats still unsure if it's a server thing. but feels like some kind of weird saving issue between versions... I'm gonna attempt to backdate (since the last version I used was only 1.7.4 and current is 1.7.5) and see if it will revert or if I'm well and truly stuck. and if I am, gonna attempt just taking note of all the bits of storage system I've got, deleting mod, then just reinstalling it and cheating that stuff back in.

**Comment by AfterRebelion** [comment]
Can confirm this, but my experience is really different from what others say.
New server with newly created world, and this happens. It is not limited to visuals, it also changes how the request table works.
![imagen](https://user-images.githubusercontent.com/559819/58640775-165ae000-82fa-11e9-9deb-02b1bee94aab.png)
Inventory is shifted by one space. The first space of the crafting grid is the output. It doesn't show the output, but if you click there, it gives you it.
The first space on the player inventory is part of the crafting grid. If you put any item there (Like in the next example), you get the normal output:
![If you put a piece of iron in this space](https://user-images.githubusercontent.com/559819/58640984-92edbe80-82fa-11e9-8134-8ad362bacfdb.png)
![You get 9 iron ingots](https://user-images.githubusercontent.com/559819/58641024-aa2cac00-82fa-11e9-85b3-85cdd131fc58.png)
 The output slot seems completely nonfunctional.

**Comment by Lothrazar** [comment]
Do you have FastWorkbench installed? I cant replicate any of these issues in the latest releaes release 
![ssss](https://user-images.githubusercontent.com/621529/58686931-10362500-8335-11e9-84a4-85de3a56e33d.gif)

**Comment by AfterRebelion** [comment]
No, I don't have FastWorkbench.
I can't confirm it happens, tested it on a newly created server right now with default settings, only Simple Storage Network and forge, and it happens.
Logs here:
https://gist.github.com/AfterRebelion/6d3ce8053f5497789fe8bebec3b062b9

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Storage-Network/issues/179 has it happneing as well, with a mod list and images

**Comment by Lothrazar** [comment]
noticed your latest log has MinecraftForge v14.23.5.2838 , im still on 
14.23.5.2768 , not sure if its related but maybe

**Comment by Lothrazar** [comment]
@AfterRebelion  does it only happen on a dedicated server?  or also single player

**Comment by AfterRebelion** [comment]
This is dedicated server only, on singleplayer it works fine.

**Comment by AfterRebelion** [comment]
Tested 1.7.6, and it seems to work as expected now.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files
